<a href="https://colab.research.google.com/github/arifroska/PrakAPM/blob/main/ANN_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import data
from google.colab import files
uploaded = files.upload()

Saving survey lung cancer.csv to survey lung cancer.csv

In [3]:
import io
import numpy as np  #import library numpy
import pandas as pd  #import library pandas
import matplotlib.pyplot as plt  #import library maplotlib
%matplotlib inline
from sklearn import metrics  #import library metrics dari modul sklearn
from sklearn.metrics import accuracy_score, confusion_matrix  #import library metrics dari modul sklearn
from sklearn.model_selection import train_test_split  #import modul train test split dari library sklearn
import seaborn as sns  #import library seaborn

data = pd.read_csv(io.BytesIO(uploaded['survey lung cancer.csv']), encoding= 'latin-1')
data.head(n=10)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
5,F,75,1,2,1,1,2,2,2,2,1,2,2,1,1,YES
6,M,52,2,1,1,1,1,2,1,2,2,2,2,1,2,YES
7,F,51,2,2,2,2,1,2,2,1,1,1,2,2,1,YES
8,F,68,2,1,2,1,1,2,1,1,1,1,1,1,1,NO
9,M,53,2,2,2,2,2,1,2,1,2,1,1,2,2,YES

In [20]:
# Import LabelEncoder
from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
data['LUNG_CANCER']=le.fit_transform(data['LUNG_CANCER'])

In [21]:
# Spliting data into Feature and
X=data[['SMOKING', 'ANXIETY', 'FATIGUE']]
y=data['LUNG_CANCER']

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test

In [22]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 0.43294515
Iteration 2, loss = 0.42652125
Iteration 3, loss = 0.42565982
Iteration 4, loss = 0.42386718
Iteration 5, loss = 0.42157638
Iteration 6, loss = 0.41951260
Iteration 7, loss = 0.41831919
Iteration 8, loss = 0.41972808
Iteration 9, loss = 0.42043710
Iteration 10, loss = 0.42084211
Iteration 11, loss = 0.42174318
Iteration 12, loss = 0.42182619
Iteration 13, loss = 0.42139270
Iteration 14, loss = 0.42125182
Iteration 15, loss = 0.42162645
Iteration 16, loss = 0.42071852
Iteration 17, loss = 0.41825759
Iteration 18, loss = 0.41590917
Iteration 19, loss = 0.41398894
Iteration 20, loss = 0.41283598
Iteration 21, loss = 0.41219952
Iteration 22, loss = 0.41209656
Iteration 23, loss = 0.41278368
Iteration 24, loss = 0.41289057
Iteration 25, loss = 0.41221148
Iteration 26, loss = 0.41107253
Iteration 27, loss = 0.41087634
Iteration 28, loss = 0.41058885
Iteration 29, loss = 0.41027374
Iteration 30, loss = 0.40987634
Iteration 31, loss = 0.40946554
Iteration 32, loss = 0.40922640
Iteration 33, loss = 0.40897464
Iteration 34, loss = 0.40881058
Iteration 35, loss = 0.40901987
Iteration 36, loss = 0.40896259
Iteration 37, loss = 0.40884035
Iteration 38, loss = 0.40868097
Iteration 39, loss = 0.40835215
Iteration 40, loss = 0.40807992
Iteration 41, loss = 0.40799347
Iteration 42, loss = 0.40761726
Iteration 43, loss = 0.40727856
Iteration 44, loss = 0.40669562
Iteration 45, loss = 0.40644717
Iteration 46, loss = 0.40698266
Iteration 47, loss = 0.40720608
Iteration 48, loss = 0.40799665
Iteration 49, loss = 0.40941705
Iteration 50, loss = 0.41018897
Iteration 51, loss = 0.41029289
Iteration 52, loss = 0.41140755
Iteration 53, loss = 0.41473266
Iteration 54, loss = 0.41878487
Iteration 55, loss = 0.42073278
Iteration 56, loss = 0.41800704
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [23]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.9247311827956989